#!/usr/bin/env bash

if [ "$1" == "--debug" ]; then
  shift
  gradle -q uberJar && \
    java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:8192 \
      -cp build/libs/web-view-components-uber-0.1.0.jar \
      org.codehaus.groovy.tools.FileSystemCompiler \
      --configscript src/main/resources/groowt/view/component/web/groovyc/groovycConfigurationScript.groovy \
      -d groovyc-out \
      "$@"
else
  gradle -q uberJar && \
    groovyc -cp build/libs/web-view-components-uber-0.1.0.jar \
      --configscript src/main/resources/groowt/view/component/web/groovyc/groovycConfigurationScript.groovy \
      -d groovyc-out \
      "$@"
fi
